apiVersion: v1
kind: Service
metadata:
  name: assistant-server
  namespace: personal-assistant
spec:
  selector:
    app: assistant-server
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
